### ISSUE TITLE
RFC assignee and sub-team

### ISSUE THREAD

**Issue by kchristidis** [christo4ferris/fabric-rfcs-proposal#2]
These are referenced in the README without an explanation of how they come to be. We'll need to address that.

- Is the RFC assignee always going to be a maintainer?
- I take it that the sub-team is not necessarily a team consisting of just maintainers. Would that be accurate?

Let's discuss how this work and I can put in the necessary changes via a new PR.

**Comment by christo4ferris** [comment]
sub-team is a Sawtooth reference, I meant to change all those to 'maintainers'. As for assignee, I think yes.

**Comment by kchristidis** [comment]
Alright, will do.
