### ISSUE TITLE
Subteam is undefined

### ISSUE THREAD

**Issue by lehors** [christo4ferris/fabric-rfcs-proposal#3]
The README refers to "subteam" but it's unclear what is considered to be a subteam.
I can see @kchristidis replaced several occurrences with maintainers so I don't know whether the remaining references are intentional or a mere oversight.

**Comment by kchristidis** [comment]
An oversight, I grepped for `sub-team` (with a dash). Will fix before EOD today. Thanks for the catch!

**Comment by kchristidis** [comment]
Submitted a fix. Have a look and LMK what you think of the "all maintainers" rule; I _think_ it should be revised.
