### ISSUE TITLE
Can't someone find who's working on an implementation in JIRA?

### ISSUE THREAD

**Issue by lehors** [christo4ferris/fabric-rfcs-proposal#4]
The README says that "If you are interested in working on the implementation for an active RFC, but cannot determine if someone else is already working on it, feel free to ask".

However, the README also says that "Every accepted RFC has an associated issue tracking its implementation in the Fabric JIRA issue tracker".

So, shouldn't you be able to find if someone else is working on the RFC implementation by checking whether the associated JIRA ticket is assigned?

**Comment by kchristidis** [comment]
Good catch.

**Comment by kchristidis** [comment]
Pushed a fix, and made that section less verbose. LMK what you think.
