### ISSUE TITLE
Reconsider "all maintainers must sign off" rule

### ISSUE THREAD

**Issue by kchristidis** [christo4ferris/fabric-rfcs-proposal#6]
As things stand today, all maintainers must sign-off before we move to FCP. I think we run the risk of being blocked more frequently than we think if we follow this rule. I propose we move to a 2/3rds rule or similar.

**Comment by C0rWin** [comment]
I think that we might just identify what Fabric component is subject of RFC and ask for sign-off from component owners.

**Comment by lehors** [comment]
I agree with @C0rWin I think identifying areas of "ownership", or at least expertise, for the maintainers would be an improvement anyway.

**Comment by kchristidis** [comment]
@C0rWin: Let's create a PR that builds on PR #5 with the changes that you recommend.

**Comment by C0rWin** [comment]
@kchristidis makes sense, will do it.

**Comment by jyellick** [comment]
I'm not strictly opposed to identifying Fabric components, and component ownership, but do we really need this to be a matter of process?  I'd suggest that maintainers are generally aware of who component experts are, and, are willing to defer to those experts where appropriate.

Simply requiring a 2/3rds, or even a simple majority sign-off, where most maintainers will end up concurring with the component experts seems fine and flexible to me.  Given rates of code review and other maintainer engagement, I even question whether a plain majority is too onerous.

**Comment by jyellick** [comment]
Does the above close this issue?
